# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MHBlog
email: maiconhenriquekcond@gmail.com
description: "Blog para armazenar itens de estudos entre outras informações que possa facilitar o aprendizado."
baseurl: "/mhblog" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: maiconhenriquekcond
github_username:  maiconkcond

# Build settings
markdown: kramdown
#permalink: /:categories/:year/:month/:day/:title
#permalink: /:year/:month/:day/:title
permalink: /:title